# Generated by Django 5.2 on 2025-04-14 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('EVENT', 'Event Creation'), ('NOTIFICATION', 'Notification')], max_length=20)),
                ('event_data', models.JSONField(blank=True, null=True)),
                ('notification_type', models.CharField(blank=True, choices=[('24_HOURS', '24 Hours (Free)'), ('48_HOURS', '48 Hours ($6.00)'), ('7_DAYS', '7 Days ($13.70)')], max_length=20, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.cart')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('24_HOURS', '24 Hours (Free)'), ('48_HOURS', '48 Hours ($6.00)'), ('7_DAYS', '7 Days ($13.70)')], default='24_HOURS', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='events.event')),
            ],
        ),
    ]
