# Generated by Django 5.2 on 2025-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
