# Generated by Django 5.2 on 2025-04-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_customuser_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='above_legal_age',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary')], default='', max_length=10),
        ),
    ]
