# Generated by Django 5.2 on 2025-04-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_customuser_above_legal_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_location',
            field=models.CharField(choices=[('none', 'None'), ('while_using', 'While Using App'), ('once', 'Once')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='allow_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='allow_photos',
            field=models.CharField(choices=[('none', 'None'), ('selected', 'Selected Photos'), ('all', 'All Photos')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_code_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
