# Generated by Django 5.2 on 2025-04-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_auto_20250405_1836'),
        ('signup', '0004_customuser_allow_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='users', to='hobbies.hobby'),
        ),
    ]
