# Generated by Django 5.2 on 2025-04-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_customuser_bio_customuser_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
