# Generated by Django 5.2 on 2025-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_customuser_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='qr_code_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
