# Generated by Django 5.2 on 2025-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_remove_customuser_qr_code_url_customuser_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
