# Generated by Django 5.2 on 2025-04-14 15:40

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_customuser_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paypal_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paypal_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paypal_refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
