"""
Django settings for kumele_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("SECRET_KEY")

# SECRET_KEY = "cce9ca4c28e9200fef39d536cc043f46"


# SECURITY WARNING: don't run with debug turned on in production!


DEBUG = os.environ.get("DEBUG", "FALSE").lower() == "true"

# For local development, override DEBUG
# DEBUG = True

APP_NAME = "Kumele"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split(" ")

# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',
#     'kumele-1.onrender.com',
#     'airedale-destined-antelope.ngrok-free.app'
# ]

SITE_ID = 2
# Application definition

INSTALLED_APPS = [
    "signup.apps.SignupConfig",
    'hobbies',
    'userprofile',
    'authenticator',
    'paypalconnections',
    'events',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google'
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE":[
            "profile",
            "email"
        ],
        "AUTH_PARAMS" : {"access_type": "online" }
    }
}

GOOGLE_OAUTH2_CLIENT_ID = os.environ.get("GOOGLE_OAUTH2_CLIENT_ID")

# GOOGLE_OAUTH2_CLIENT_ID = "675550706414-i9f1j9l4t9ifc40o9gnr59pt4kvdq907.apps.googleusercontent.com"



AUTHENTICATION_BACKENDS=[
    'django.contrib.auth.backends.ModelBackend',
    "allauth.account.auth_backends.AuthenticationBackend"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'kumele_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kumele_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kumele',
        'USER': 'kumele_user',
        'PASSWORD': 'kumele123',
        'HOST': 'localhost',  # Use '127.0.0.1' or the IP address of the server
        'PORT': '5432',       # Default PostgreSQL port
    }
}

database_url = os.environ.get("DATABASE_URL")

# DATABASES["default"] = dj_database_url.parse("postgresql://kumele_user:P2ms0XoAwextIiDv8k98zYkMDBML6Zrr@dpg-cvpc5e49c44c73c1g800-a.oregon-postgres.render.com/kumele_gzza")

DATABASES["default"] = dj_database_url.parse(database_url)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # or your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tejashkatuwal99@gmail.com'
EMAIL_HOST_PASSWORD = 'aepiayqwdylqdkag'

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:8000',
    'http://localhost:5174',
    'https://airedale-destined-antelope.ngrok-free.app'
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = False  # For development
SESSION_COOKIE_HTTPONLY = True

# Also add these settings
# CORS_ALLOW_CREDENTIALS = True
# CORS_EXPOSE_HEADERS = ['X-API-Key']

# # Add this to ensure proper origin handling
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Add this for local development
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

AUTH_USER_MODEL = 'signup.CustomUser'

LOGIN_REDIRECT_URL = "/auth/google-signin/"
LOGOUT_REDIRECT_URL = "/"



BASE_DIR = Path(__file__).resolve().parent.parent

# Media files (already set, just for reference)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# PAYPAL_CLIENT_ID = "ATeGbYIYguJuvRjL0Dkqr-cIN1vkPB8BxrxSvcEdaN9Ln9_Qe8RmH3XUGRl1a_Bf2-R8FshI9gKwW11Z"
PAYPAL_CLIENT_ID = os.environ.get("PAYPAL_CLIENT_ID")
# PAYPAL_CLIENT_SECRET = "EDOIndz3kSL5mfW4YL_nU4wbPBXFc9lEbWkTBM4HjFs3OJp0T2oie_L7zLLVyvS4iTIY7yOWHFmjFhwy"
PAYPAL_CLIENT_SECRET = os.environ.get("PAYPAL_CLIENT_SECRET")
# PAYPAL_MODE = "sandbox"
PAYPAL_MODE = os.environ.get("PAYPAL_MODE")
# FRONTEND_URL = "http://localhost:5174"  #"https://airedale-destined-antelope.ngrok-free.app" 
FRONTEND_URL = os.environ.get("FRONTEND_URL")


# PAYPAL_WEBHOOK_SECRET = "7XA96399C6147174U"
# PAYPAL_AUTH_URL = "https://www.sandbox.paypal.com/connect"  # Use "https://www.paypal.com/connect" for production
# PAYPAL_TOKEN_URL = "https://api-m.sandbox.paypal.com/v1/oauth2/token"  # Use "https://api-m.paypal.com" for production
# PAYPAL_SCOPES = "openid email https://uri.paypal.com/services/payouts"
# PAYPAL_REDIRECT_URI = "https://airedale-destined-antelope.ngrok-free.app/auth/paypal/callback/"
# PAYPAL_PARTNER_MERCHANT_ID = "7PSXWNYFSUNP4"

# FIELD_ENCRYPTION_KEY = 'YxvnSdzJGaruJLG8t0mpJE70jXothUeKTLrYAyJjr7w='
FIELD_ENCRYPTION_KEY = os.environ.get("FIELD_ENCRYPTION_KEY")
