from django.urls import path
from .views import (SignupView,
    VerifyEmailView, 
    GoogleSignInView, 
    UpdatePermissionsView, 
    SetUsernameView, 
    DeleteUserAccountView,
    LoginView, 
    UpdateUserDetailsView,
    PasskeyRegistrationOptionsView,
    PasskeyRegistrationVerifyView,
    PasskeyLoginOptionsView,
    PasskeyLoginVerifyView,
    PasskeyTestPageView,
    PayPalConnectView,
    PayPalCallbackView,
    PayPalDisconnectView,
    PrivacyPolicyView,
    UserAgreementView,
    UserMedalsView
)

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('verify-email/', VerifyEmailView.as_view(), name='verify_email'),
    path('google-signin/', GoogleSignInView.as_view(), name='google_signin'),
    path('update-permissions/', UpdatePermissionsView.as_view(), name='update-permissions'),
    path('set-username/', SetUsernameView.as_view(), name='set-username'),
    path('login/', LoginView.as_view(), name='login'),
    path('update-user-details/', UpdateUserDetailsView.as_view(), name='update-user-details'),
    path('passkey/register/options/', PasskeyRegistrationOptionsView.as_view(), name='passkey_register_options'),
    path('passkey/register/verify/', PasskeyRegistrationVerifyView.as_view(), name='passkey_register_verify'),
    path('passkey/login/options/', PasskeyLoginOptionsView.as_view(), name='passkey_login_options'),
    path('passkey/login/verify/', PasskeyLoginVerifyView.as_view(), name='passkey_login_verify'),
    path('passkey-test-page/', PasskeyTestPageView.as_view(), name='passkey-test-page'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='PrivacyPolicy'),
    path('useragreement/', UserAgreementView.as_view(), name='UserAgreement'),
    path('account/delete/', DeleteUserAccountView.as_view(), name='delete-account'), 
    path('paypal/connect/', PayPalConnectView.as_view(), name='paypal-connect'),
    path('paypal/callback/', PayPalCallbackView.as_view(), name='paypal-callback'),
    path('paypal/disconnect/', PayPalDisconnectView.as_view(), name='paypal-disconnect'),
    path('medals/', UserMedalsView.as_view(), name='user-medals'),

]