# Generated by Django 5.2 on 2025-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0005_hobby_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
