# Generated by Django 5.2 on 2025-04-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypalconnections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypalaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='paypalaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='paypalaccount',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='paypalaccount',
            name='token_expiry',
        ),
    ]
